// Here we define dependencies we need for the program
var fs = require('fs'); // fs stands for the File System of the machine 
const Path = require("path"); // Allows natively formatting file paths

// This file defines the logic and 
// utilization of the previously
// generated population storage files.

// Our study has a total duration of
// 24 months or two years. We will
// divide this into six stages of
// four months each in which adverse
// effects may develop.

// We detect the population data created by the previous application
// Please make sure that the data folder only contains .json files that 
// were generated by the the first stage population generator written in Go.
let Files  = [];

// We create a folder to store the future final data of the three trials for analysis

let dir = './data/final/'

if (fs.existsSync(dir)) {
    console.log("The folder was found")
    fs.rmdirSync(dir, {recursive: true})
    fs.mkdirSync(dir);
} else {
    console.log("The folder was not found")
    fs.mkdirSync(dir);
}
    
function ThroughDirectory(Directory) {
    fs.readdirSync(Directory).forEach(File => {
        const Absolute = Path.join(Directory, File);
        if (fs.statSync(Absolute).isDirectory()) return ThroughDirectory(Absolute);
        else return Files.push(Absolute);
    });
}

ThroughDirectory("./data/initial/");
// We briefly report that we successfully disovered the population data files.
console.log(`\nThe simulation has now been launched with the following discovered data files:\n\n- ${Files[0]}\n- ${Files[1]}\n- ${Files[2]}\n`)

// This is the base function that will choose events based on probability
function eventSimulator(proabability) {
    var randomchance = Math.random();
    var sum = 0;
    proabability.forEach(function(chance) {
        sum+=chance;
    });
    var chance = 0;
    for(var i=0; i<proabability.length; i++) {
        chance+=proabability[i]/sum;
        if(randomchance<chance) {
            return i;
        }
    }
}

// First we create the probability options model for the severity of the adverse effect based on cited statistics

// We use Binomial Probability to consider the amount of event opportunities may happen. Since the 24 month period
// is being divided into six stages of four months each, there are six opportunities to encounter adverse effects

// 65.82% of immunotherapy patients developed any adverse effects.
var eventProbabilityImmuno = ["adverse", "none"];
var eventProbabilityValuesImmuno = [66, 34];

// 85.19% of chemotherapy patients developed any adverse effects.
var eventProbabilityChemo = ["adverse", "none"];
var eventProbabilityValuesChemo = [85, 15];

// Fatality probabilities for Immunotherapy and Chemotherapy 
var fatalProbabilityChemo = ["fatality", "none"];
var fataleventProbabilityValuesChemo = [87, 9913];

var fatalProbabilityImmuno = ["fatality", "none"];
var fataleventProbabilityValuesImmuno = [128, 9872];

// We create an array container to store the future concluding information
let patientTrialOutcome = {}

// We define this to run for each of the three trial data files
Files.forEach(function(datafile, index) {
    console.log(`Running the analysis for trial data: ` + (index + 1))
    trialData = JSON.parse(fs.readFileSync(Files[index], "utf8"));
    for (item in trialData) {
       // Here we run the simulation logic for each patient of the running trial
       // We do this in the previously mentioned six stages representing each four months
        let experienceAdverseEvents = false

       function stageSimulation() {
           // The simulation functions with different statistical probabilities
           // depending on the medication each patient takes.
            if (trialData[item].medication == 'ipilimumab') {
                if (eventProbabilityImmuno[eventSimulator(eventProbabilityValuesImmuno)] == 'adverse') {
                    experienceAdverseEvents = true
                    // This is the logic that occurs 
                } else { // If there is no adverse effect report none
                }
            } else if (trialData[item].medication == 'nivolumab') {
                if (eventProbabilityImmuno[eventSimulator(eventProbabilityValuesImmuno)] == 'adverse') {
                    experienceAdverseEvents = true
                } else { // If there is no adverse effect do nothing
                }
            } else if (trialData[item].medication == 'doxycycline') {
                if (eventProbabilityChemo[eventSimulator(eventProbabilityValuesChemo)] == 'adverse') {
                    experienceAdverseEvents = true
                } else { // If there is no adverse effect do nothing
                }
            }
       }

       function fatalitySimulation() {
           // The rate of fatality for a patient undergoing immunotherapy is approximated 
           // to be 0.87%, as compared with that of chemotherapy, 1.28% [Source 21]
            if (trialData[item].medication == 'ipilimumab' || 'nivolumab' ) {
                if (eventProbabilityImmuno[eventSimulator(eventProbabilityValuesImmuno)] == 'fatality') {
                    return true
                } else {
                    return false
                }
            } else if (trialData[item].medication == 'doxycycline') {
                if (eventProbabilityChemo[eventSimulator(eventProbabilityValuesChemo)] == 'fatality') {
                    return true
                } else {
                    return false
                }
            }
       }


       for (i = 0; i < 4; i++) {
        stageSimulation()
       }

       // Store this information in the final container that we prepare documentation
       // in charts and graphs for later.

       let patientinfo = {
        // First we define the previous initial data
        "name": item.name,
        "agegroup": item.agegroup,
        "age": item.age,
        "gender": item.gender,
        "severity": item.severity,
        "ethnicity": item.ethnicity,
        "medication": item.medication,
        // Now we define the new results in additional properties
        // for later analysis
        "health": 100,
        "adverseevents": experienceAdverseEvents,
        "fatality": fatalitySimulation(),
       }
       let patientobjectidentifier = String(item.name)
       patientTrialOutcome.patientobjectidentifier = patientinfo;
       console.log(patientinfo)
    } 

});